### ISSUE TITLE
Crash when you use any crafting station or slab (1.17.1)

### ISSUE THREAD

**Issue by Facejif** [shedaniel/improved-stations#28]
https://gist.githubusercontent.com/natanfudge/9a533ba5a7ab93753f7490a5ee08ed54/raw/7e2614393ced56a72a2357823ff90c2824fc5432/crash.txt
Here's crash log. Tested without other mods - same thing!

**Comment by psecegm** [comment]
Same behavior, different OS, Chip and 
[crash-2021-07-10_14.06.48-server.txt](https://github.com/shedaniel/improved-stations/files/6795971/crash-2021-07-10_14.06.48-server.txt)
