### ISSUE TITLE
Client Crash when someone placing a station on a server (Rendering Block Entity)

### ISSUE THREAD

**Issue by MasterEnderman** [shedaniel/improved-stations#3]
Minecraft: 1.15.1
Fabric: 0.7.3-build.176
Fabric API : 0.4.27-build.286
Improved Stations: 1.2.1
Crash-Report: https://pastebin.com/2dBzYeSC

The Client crashes as soon as another player is placing down a station near the first player.

**Comment by shedaniel** [comment]
Made it not crash in 1.2.3, still need to find out why it doesn't work.

**Comment by CerulanLumina** [comment]
The regular crafting station doesn't have the slab type property - https://github.com/shedaniel/improved-stations/blob/4c1297936e90f5625a6dfaf19f762d0538c5035f/src/main/java/me/shedaniel/istations/blocks/entities/renderer/CraftingStationBlockEntityRenderer.java#L40
